/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/candidate` | `/candidate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/employee` | `/employee`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/employee/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/employee/document-viewer`; params?: Router.UnknownInputParams; } | { pathname: `/employee`; params?: Router.UnknownInputParams; } | { pathname: `/employee/my-documents`; params?: Router.UnknownInputParams; } | { pathname: `/employee/profile`; params?: Router.UnknownInputParams; } | { pathname: `/employee/salary-slips`; params?: Router.UnknownInputParams; } | { pathname: `/employee/upload-documents`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/candidate` | `/candidate`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/employee` | `/employee`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `/employee/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/employee/document-viewer`; params?: Router.UnknownOutputParams; } | { pathname: `/employee`; params?: Router.UnknownOutputParams; } | { pathname: `/employee/my-documents`; params?: Router.UnknownOutputParams; } | { pathname: `/employee/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/employee/salary-slips`; params?: Router.UnknownOutputParams; } | { pathname: `/employee/upload-documents`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/candidate${`?${string}` | `#${string}` | ''}` | `/candidate${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/employee${`?${string}` | `#${string}` | ''}` | `/employee${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/jobs${`?${string}` | `#${string}` | ''}` | `/jobs${`?${string}` | `#${string}` | ''}` | `/employee/dashboard${`?${string}` | `#${string}` | ''}` | `/employee/document-viewer${`?${string}` | `#${string}` | ''}` | `/employee${`?${string}` | `#${string}` | ''}` | `/employee/my-documents${`?${string}` | `#${string}` | ''}` | `/employee/profile${`?${string}` | `#${string}` | ''}` | `/employee/salary-slips${`?${string}` | `#${string}` | ''}` | `/employee/upload-documents${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/candidate` | `/candidate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/employee` | `/employee`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `/employee/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/employee/document-viewer`; params?: Router.UnknownInputParams; } | { pathname: `/employee`; params?: Router.UnknownInputParams; } | { pathname: `/employee/my-documents`; params?: Router.UnknownInputParams; } | { pathname: `/employee/profile`; params?: Router.UnknownInputParams; } | { pathname: `/employee/salary-slips`; params?: Router.UnknownInputParams; } | { pathname: `/employee/upload-documents`; params?: Router.UnknownInputParams; };
    }
  }
}
